all: svd_bias.cpp svd_bias_simult_update.cpp
	g++ -g -Wall -O2 -o svd_bias svd_bias.cpp
	g++ -g -Wall -O2 -o svd_bias_simult_update svd_bias_simult_update.cpp

clean: 
	$(RM) svd_bias
	$(RM) svd_bias_simult_update